# Site settings
title: Cloud Storage For My Brain
header-img: img/home-clouds.jpg
email: bbutton@agilestl.com
description: "My eventually consistent thoughts and musings"
baseurl: ""
url: "http://bbutton.github.io"
twitter_username: brianbuttonxp
github_username:  bbutton
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
